### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by ablwr** [avpreserve/avcc#1]
When installing AVCC, I get this error: 

```
Fatal error: Uncaught exception 'Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException' with message 'You have requested a non-existent parameter "stripe_publishkey".' in /Users/ashleyblewer/Development/projects/avcc/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:108
Stack trace:
#0 /Users/ashleyblewer/Development/projects/avcc/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(234): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('stripe_publishk...')
#1 /Users/ashleyblewer/Development/projects/avcc/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(205): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%stripe_publish...', Array)
#2 /Users/ashleyblewer/Development/projects/avcc/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(195): Symfony\Component\DependencyInjection\ in /Users/ashleyblewer/Development/projects/avcc/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 108
```

and cannot proceed! I am on a MacBook Pro running Yosemite and Composer version 1.3.2 2017-01-27 18:23:41. My parameters match those in the installation guide (Step 4). I tried removing the stripe_publishkey line in config.yml and re-installing / updating but this didn't resolve the problem.

**Comment by smntb** [comment]
We recently added a feature for payments that uses stripe. We just updated the documentation and also the default parameter options. Please pull the latest changes and try to run composer install again that will solve your problem.

**Comment by ablwr** [comment]
Thanks! I sent a PR for a typo in the documentation. Also since I hadn't created a MySQL database called symfony in advance, I had to run `php app/console doctrine:schema:create --dump-sql` instead of the update command listed.

Is there a php command to run as a server? I know Symfony comes with a server function built-in but I believe it's for only higher versions of PHP.

**Comment by smntb** [comment]
Thanks, Yes you can run the following command to run the application as a server
 php app/console server:run

**Comment by ablwr** [comment]
😅 So easy, thank you!
